deploy-ec2:
  runs-on: ubuntu-latest
  needs: docker-build   # deploy only if build+test passed

  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@v0.1.10
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
        # ensure app folder exists
        mkdir -p ~/app
        cd ~/app

        # clone repo if first time
        if [ ! -d "devops-ci-cd-main" ]; then
          git clone https://github.com/<your-username>/<your-repo>.git devops-ci-cd-main
        fi

        # update code
        cd devops-ci-cd-main
        git pull origin main

        # stop and remove old container if running
        docker stop fitness-app || true
        docker rm fitness-app || true

        # build and run fresh container
        docker build -t fitness-app .
        docker run -d -p 5000:5000 --name fitness-app fitness-app
